eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

server:
  port: 9094

spring:
  profiles:
    active: remote